services:
  simulator:
    image: simulator:latest
    container_name: simulator
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - /home/ubuntu/apps/simulator/logs:/app/logs
      - /home/ubuntu/apps/simulator/static:/app/static
      - /home/ubuntu/apps/simulator/simulator.db:/app/simulator.db
      - /home/ubuntu/apps/simulator/config/conf.toml:/app/config/conf.toml
      - /home/ubuntu/apps/simulator/logs:/app/logs